name: foodbar_user
description: Foodbar is a reservation system for restaurants, and this is an Flutter App for this system. 
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.0
  http: ^0.13.5
  intro_slider: ^2.2.8
  shared_preferences: ^0.5.6+1
  after_layout: ^1.0.7+2
  font_awesome_flutter: ^8.8.1

  
  foodbar_flutter_core:
    #git: https://github.com/navidshad/foodbar_flutter_core.git
    path: '../ui_core'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.16.0

  flutter_launcher_icons: "^0.7.4"
  flutter_launcher_name: "^0.0.1"

# must run "flutter pub run flutter_launcher_icons:main"
# after change this
flutter_icons:
    android: "launcher_icon" 
    ios: true
    image_path: "assets/icon/icon.png"

# must run "flutter pub run flutter_launcher_name:main"
# after change this
flutter_launcher_name:
  name: "Haiku Shushi"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/logo.png
   - assets/images/logo_wide.png
   - assets/images/logo_vertical.png

   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  FoodBarIcons
      fonts:
      - asset: assets/fonts/FoodBarIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
