/// Flutter icons FoodBarIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FoodBarIcons
///      fonts:
///       - asset: fonts/FoodBarIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class FoodBarIcons {
  FoodBarIcons._();

  static const _kFontFam = 'FoodBar';

  static const IconData like = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData like_flat = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData star_empty = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData phone_android = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData shopping_bag = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData mail_1 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData shopping_bag_not_empty = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData success = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData error = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData spoon_and_fork = const IconData(0xe80b, fontFamily: _kFontFam);
}
